name: test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl: ["5.40", "5.38", "5.36", "5.34", "5.32", "5.30", "5.28"]
    name: Perl ${{ matrix.perl }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

      - name: Install dependencies
        run: |
          cpanm -nq --installdeps --with-develop --with-recommends .
          cpanm -nq Devel::Cover Devel::Cover::Report::Coveralls

      - name: Run tests with coverage
        run: |
          cover -test

      - name: Upload coverage to Coveralls
        if: matrix.perl == '5.40'  # Upload only once to avoid duplicate reports
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cover -report coveralls
